name: CI/CD Pipeline with AWS CodeDeploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the commit hash
        id: get_commit
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Get the current timestamp
        id: get_timestamp
        run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"

      - name: Build and package application
        run: |
          # Add build commands here if needed
          zip -r StartButtonApp-dev-${{ steps.get_commit.outputs.sha }}-${{ steps.get_timestamp.outputs.timestamp }}.zip .

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: testing-repo
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "./"

      - name: Deploy to Development
        if: github.ref == 'refs/heads/dev'
        uses: webfactory/create-aws-codedeploy-deployment@v1
        with:
          application: testing
          deployment-group: Development-StartButton
          s3-location: bucket=testing-repo,key=StartButtonApp-dev-${{ steps.get_commit.outputs.sha }}-${{ steps.get_timestamp.outputs.timestamp }}.zip,bundleType=zip
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
